name: test
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libncurses5-dev libncursesw5-dev

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        go build -ldflags "-linkmode external -extldflags '-static -lncurses'" -o intop.amd64 ./main